# Welcome to Jekyll!
# Site settings
title: Something Creative 
email: contact@createsomethingcreative.com
description: > # this means to ignore newlines until "baseurl:"
 Cause our lives are dope and we do dope shit. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://createsomethingcreative.com" # the base hostname & protocol for your site
twitter_username: somethingcreative
github_username:  something-creative

# Build settings
markdown: kramdown
theme: minima
